[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
test01 = "6p1a6Nq66DgLomDJWYSyqamaAyUe5FfQcdnhSXk41ieh"
together = "6X1bbuhSvquPbM3sByfnMNfT2MXUZX5BvFHSAJx4x1yN"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://api.devnet.solana.com"
wallet = "/home/arjanjohan/.config/solana/id.json"

[scripts]
test = "../node_modules/.bin/nx run anchor:jest"

[test]
startup_wait = 5000
shutdown_wait = 2000
upgradeable = false

[test.validator]
bind_address = "127.0.0.1"
ledger = ".anchor/test-ledger"
rpc_port = 8899
